Basic CI pipeline
studyportals/goldeneye pull request #8
Opened 2021-02-08 10:40 UTC by dandobrescu

Please see the README.md updates, as it should properly describe the functionality that's been added through the UML diagram. 

The purpose is to achieve high flexibility in creating the different types of pipelines (testing,producation,pr) for the services we need to support (frontend, backend, docker). 

As part of my PDP, I have tried to achieve this flexibility through the builder pattern with some factory flavors, while making use of the composition pattern associated with the CDK constructs. Please review the "engine" of the whole pipeline creation as I believe it is crucial for this part to work flawless.

2021-02-08 11:29 UTC, JensStudyportals approved these changes

2021-02-09 13:18 UTC, Stormyy requested changes

2021-02-09 13:18 UTC, Stormyy commented on cicd/README.md
> +_(CI/CD)_ account that will creating the infrastructure by assuming a role in the trusted accounts
```suggestion
_(CI/CD)_ account that will be creating the infrastructure by assuming a role in the trusted accounts
```

2021-02-09 13:18 UTC, Stormyy commented on cicd/src/constructs/environment/default-build.ts
> +export const parseArn = (arn: string):
I would either move this to its own file or add it as a method to the DefaultBuildProject  class if this is going to be the only place to parse an ARN

2021-02-09 13:18 UTC, Stormyy commented on cicd/src/constructs/environment/notifications.ts
> +		buildProjects.map((project: IProject) => {
Probably better use foreach instead of map. Because map is ment to change the item.

2021-02-09 13:18 UTC, Stormyy commented on cicd/src/constructs/environment/notifications.ts
> +	private setupReportingFunction(buildProjects: IProject[]): Lambda.Function {
This method is doing alot. Can some of this be extracted to multiple methods?

2021-02-09 13:18 UTC, Stormyy commented on cicd/src/constructs/environment/notifications.ts
> +		buildProjects.map((project: IProject) => {
probably can be extracted to a another method such as addCodebuildRolePolicies(function, codebuild)

2021-02-09 13:22 UTC, JensStudyportals commented on cicd/src/constructs/environment/notifications.ts
> +		buildProjects.map((project: IProject) => {
Good catch, this is true

2021-02-11 08:45 UTC, dandobrescu commented
Thanks for the reviews, I've pushed a commit that should tackle the above issues

2021-02-11 09:35 UTC, MikePv approved these changes

2021-02-11 11:21 UTC, Stormyy approved these changes

2021-02-12 14:23 UTC, merged